pipeline {
    agent any
    stages {
      stage ('paso 1') {
        steps{
          /*dir("jobs/dockerweb/"){
              java holaMundo.java
          }*/
            step{
              script{
                cd jobs/dockerweb & java holaMundo.java
              }
            }
            

        }	
      } 
    }
}
