pipeline {
    agent {label 'develop'}

	enviroment {
        appName = "variable"
    }

    stages {
		stage ('paso 1') {
			steps{
				dir("jobs/dockerweb"){
            java holaMundo.java
        }
        script{
					
				}
			}	
		} 
    }
   post {
      always {          
          deleteDir()
           sh "echo 'fase always'"
      }
      success {
            sh "echo 'fase success'"
        }

      failure {
            sh "echo 'fase failure'"
      }
      
    }
}
