pipeline {
    agent {label 'master'}
    stages {
      stage ('TEST') {
        steps{
          /*dir("jobs/dockerweb/"){
              java holaMundo.java
          }*/
              script{
                cd jobs/dockerweb & holaMundo.java
              }
        }	
      } 
    }
}
